name: build
on:
  pull_request:
    branches:
      - "main"

jobs:
  build-browser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./browser/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./browser
        run: pnpm i

      - name: Check TypeScript
        working-directory: ./browser
        run: pnpm ts-check

      - name: Build
        working-directory: ./browser
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Spacy Language Model
        run: |
          python -m spacy download en_core_web_sm
          python -m spacy download zh_core_web_sm

      - name: Run unit tests
        run: python test.py